### ISSUE TITLE
[Question] To paper presentation on [Verifying Correct Usage of Context-Free API Protocols, POPL'19]

### ISSUE THREAD

**Issue by goodtaeeun** [prosyslab-classroom/is593-2022-spring#30]
When counterexamples are detected in the target code, it was mentioned that the SMT solver checks whether this counterexample is fake or not. To me, this seems to imply that SMT solver can provide the ground truth of the given target code's validity. Then why not just use SMT solver to verify the target code?

**Comment by sujin0529** [comment]
First of all, the validity of a program cannot be checked directly using the SMT solver. Therefore, the approach of this paper was to express the API usage of the program in CFG(context-free grammar). At this time, PCFA(predicted control flow automaton) which extract from the given target code is sound about API usage. So, the SMT solver is used to reduce the wrong path that does not exist in the spec(Gs).

I hope this answer was helpful.

**Comment by goodtaeeun** [comment]
Amazing! Thanks a lot.

**Comment by KihongHeo** [comment]
Good job! Let me add more explanation.
She said

> the validity of a program cannot be checked directly using the SMT solver.

More precisely, program properties can be expressed using a first-order logic. However, checking validity of FOL is an undecidable problem. Then what should we do?

Remember the lectures for first-order logic. We can give up either automation, termination or exactness. 
Here, PCFA (i.e., a model) is chosen to give up exactness and abstract the original semantics. This is sound with respect to the original semantics. That means the following is guaranteed: "if a property abstractly written in PCFA is valid => the actual property is valid."

Then what happens if a property is not verified with PCFA? Either there exists a real bug or this alarm is spurious. This can be checked by SMT solvers. If it turns out to be a spurious one, the model (PCFA) will be refined to describe more detailed semantics of the program. 

This is a typical process of (symbolic) model checking and called CEGAR (counter-example guided abstraction refinement). But this refiment process may not terminate (i.e., keep refining infinitely).
